project:
  type: website
  output-dir: docs

website:
  title: "Gapminder Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life Expectancy vs GDP
      - href: life-population.qmd
        text: Life Expectancy vs Population
      - href: country.qmd
        text: Country Analysis

format:
  html:
    theme: cosmo
